<?php

return [
    'types' => [
        'retail' => [
            'name' => 'Retail / Shop / Kiosk',
            'group' => 'commerce',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'cashbook', 'debtors', 'cashier_shifts', 'petty_cash', 'loyalty', 'refunds', 'multi_payment_methods', 'barcode_labels'],
        ],
        'supermarket' => [
            'name' => 'Supermarket',
            'group' => 'commerce',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'cashbook', 'debtors', 'promotions', 'cashier_shifts', 'petty_cash', 'loyalty', 'refunds', 'multi_payment_methods', 'barcode_labels'],
        ],
        'pharmacy' => [
            'name' => 'Pharmacy',
            'group' => 'health',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'cashbook', 'debtors', 'prescriptions', 'expiry_tracking'],
        ],
        'agro_dealer' => [
            'name' => 'Agro Dealer',
            'group' => 'agriculture',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'seasonal_stock', 'batch_tracking'],
        ],
        'restaurant' => [
            'name' => 'Restaurant',
            'group' => 'hospitality',
            'modules' => ['dashboard', 'pos', 'inventory', 'orders', 'customers', 'reports', 'kitchen', 'recipes', 'waiter_shifts', 'table_reservations', 'split_bills', 'food_waste'],
        ],
        'hotel' => [
            'name' => 'Hotel / Guest House',
            'group' => 'hospitality',
            'modules' => ['dashboard', 'bookings', 'rooms', 'customers', 'reports', 'billing', 'cashbook', 'housekeeping', 'maintenance_requests', 'room_inspections', 'shift_logs', 'reservation_calendar'],
        ],
        'clinic' => [
            'name' => 'Clinic / Health Facility',
            'group' => 'health',
            'modules' => ['dashboard', 'patients', 'consultations', 'billing', 'prescriptions', 'reports', 'appointments', 'triage', 'doctor_notes', 'treatment_plans', 'follow_ups', 'insurance_records'],
        ],
        'laboratory' => [
            'name' => 'Laboratory / Diagnostic Centre',
            'group' => 'health',
            'modules' => ['dashboard', 'patients', 'tests', 'results', 'billing', 'reports', 'result_approval', 'technician_assignment', 'reference_ranges', 'barcode_labels', 'turnaround_reports'],
        ],
        'logistics' => [
            'name' => 'Logistics Company',
            'group' => 'mobility',
            'modules' => ['dashboard', 'fleet', 'dispatch', 'trip_sheets', 'route_stops', 'fuel_logs', 'maintenance', 'settlements', 'reports', 'profitability', 'receivables'],
        ],
        'delivery_company' => [
            'name' => 'Delivery Company / Courier',
            'group' => 'mobility',
            'modules' => ['dashboard', 'deliveries', 'fleet', 'dispatch', 'riders', 'investors', 'reports', 'settlements', 'cashbook', 'otp_confirmation', 'rider_wallets', 'complaints', 'route_efficiency', 'parcel_ageing', 'customer_tracking'],
        ],
        'warehouse' => [
            'name' => 'Warehouse',
            'group' => 'general',
            'modules' => ['dashboard', 'inventory', 'orders', 'distributions', 'reports'],
        ],
        'ngo_warehouse' => [
            'name' => 'Warehouse',
            'group' => 'non_profit',
            'modules' => ['dashboard', 'inventory', 'orders', 'distributions', 'reports'],
        ],
        'wholesale' => [
            'name' => 'Distributor / Wholesale',
            'group' => 'commerce',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'orders', 'reports', 'route_sales', 'sales_reps', 'bulk_pricing', 'stock_transfers', 'customer_credit'],
        ],
        'commodity' => [
            'name' => 'Commodity Business',
            'group' => 'commerce',
            'modules' => ['dashboard', 'trading_desk', 'lots', 'price_board', 'inventory', 'customers', 'suppliers', 'settlements', 'warehouse', 'reports', 'quality_grading', 'moisture_tracking', 'shrinkage_control'],
        ],
        'textile' => [
            'name' => 'Textile / Fashion / Kwari Market',
            'group' => 'commerce',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'reports', 'pricing_tiers', 'tailoring_jobs', 'measurements', 'style_orders', 'consignment_stock'],
        ],
        'pure_water_factory' => [
            'name' => 'Pure Water Factory',
            'group' => 'manufacturing',
            'modules' => ['dashboard', 'production', 'inventory', 'suppliers', 'expenses', 'reports', 'distribution', 'quality_checks', 'energy_costs', 'packaging_inventory', 'downtime_tracking', 'batch_costing', 'wastage_logs'],
        ],
        'grain_milling' => [
            'name' => 'Grain Milling / Processing',
            'group' => 'manufacturing',
            'modules' => ['dashboard', 'milling', 'inventory', 'suppliers', 'purchases', 'expenses', 'reports', 'yield_tracking', 'byproduct_tracking', 'wastage_logs'],
        ],
        'leather_trading' => [
            'name' => 'Leather / Hides & Skins',
            'group' => 'manufacturing',
            'modules' => ['dashboard', 'tanning', 'inventory', 'suppliers', 'purchases', 'customers', 'expenses', 'reports', 'yield_tracking', 'reject_tracking'],
        ],
        'livestock' => [
            'name' => 'Livestock Farm',
            'group' => 'agriculture',
            'modules' => ['dashboard', 'animals', 'feeding', 'health', 'breeding', 'reports', 'weight_tracking', 'milk_production', 'disease_logs', 'medication_records', 'pen_management'],
        ],
        'livestock_market' => [
            'name' => 'Livestock Trading / Market',
            'group' => 'commerce',
            'modules' => ['dashboard', 'market_transactions', 'holding_pen', 'customers', 'suppliers', 'expenses', 'reports', 'weight_tracking'],
        ],
        'farm' => [
            'name' => 'Crop Farming / Agribusiness',
            'group' => 'agriculture',
            'modules' => ['dashboard', 'plots', 'planting_cycles', 'inputs', 'harvest', 'reports'],
        ],
        'service' => [
            'name' => 'Service Business',
            'group' => 'services',
            'modules' => ['dashboard', 'bookings', 'invoices', 'jobs', 'customers', 'reports', 'staff_assignments', 'job_completion', 'invoice_follow_up'],
        ],
        'mobile_agent' => [
            'name' => 'Mobile Agent / POS Business',
            'group' => 'fintech',
            'modules' => ['dashboard', 'transactions', 'cashbook', 'liquidity', 'settlements', 'fraud_logs', 'reports', 'float_requests', 'reversal_logs', 'commission_tiers', 'agent_ranking'],
        ],
        'school' => [
            'name' => 'School / Training Centre',
            'group' => 'education',
            'modules' => ['dashboard', 'students', 'classes', 'attendance', 'fees', 'reports', 'academic_sessions', 'subjects', 'score_entry', 'report_cards', 'promotion', 'teacher_timetable'],
        ],
        'construction' => [
            'name' => 'Building Materials Business',
            'group' => 'commerce',
            'modules' => ['dashboard', 'inventory', 'categories', 'customers', 'contractors', 'suppliers', 'quotations', 'orders', 'deliveries', 'credit_sales', 'yard_stock', 'transfers', 'expenses', 'price_management', 'reports'],
        ],
        'fuel_business' => [
            'name' => 'Fuel / Energy Business',
            'group' => 'energy',
            'modules' => ['dashboard', 'inventory', 'pump_sales', 'shift_reconciliation', 'reports', 'cashbook', 'nozzle_readings', 'tank_dipping', 'wet_stock_variance', 'price_change_logs', 'anomaly_alerts'],
        ],
        'beauty' => [
            'name' => 'Beauty / Salon / Barbing',
            'group' => 'services',
            'modules' => ['dashboard', 'appointments', 'services', 'inventory', 'customers', 'commissions', 'reports', 'product_usage', 'stylist_wallets', 'rebooking'],
        ],
        'mixed' => [
            'name' => 'Mixed Business',
            'group' => 'general',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'cashbook', 'cash_entries', 'follow_ups', 'daily_targets', 'collections', 'owner_controls'],
        ],
        'general' => [
            'name' => 'General SME',
            'group' => 'general',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'cashbook', 'cash_entries', 'follow_ups', 'daily_targets', 'collections', 'owner_controls'],
        ],
        'pure_water_retail' => [
            'name' => 'Pure Water Retail',
            'group' => 'commerce',
            'modules' => ['dashboard', 'pos', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'wholesale', 'pricing_tiers', 'crate_tracking', 'package_movements', 'branch_transfers', 'retailer_pricing'],
        ],
    ],
    'demo_accounts' => [
        'admin' => ['email' => 'admin@taska.local', 'name' => 'Taska Admin', 'business_type' => null],
        'retail' => ['email' => 'retail@taska.local', 'name' => 'Retail Owner', 'business_type' => 'retail'],
        'supermarket' => ['email' => 'supermarket@taska.local', 'name' => 'Supermarket Owner', 'business_type' => 'supermarket'],
        'pharmacy' => ['email' => 'pharmacy@taska.local', 'name' => 'Pharmacy Owner', 'business_type' => 'pharmacy'],
        'agro_dealer' => ['email' => 'agro@taska.local', 'name' => 'Agro Owner', 'business_type' => 'agro_dealer'],
        'restaurant' => ['email' => 'restaurant@taska.local', 'name' => 'Restaurant Owner', 'business_type' => 'restaurant'],
        'hotel' => ['email' => 'hotel@taska.local', 'name' => 'Hotel Owner', 'business_type' => 'hotel'],
        'clinic' => ['email' => 'clinic@taska.local', 'name' => 'Clinic Owner', 'business_type' => 'clinic'],
        'laboratory' => ['email' => 'lab@taska.local', 'name' => 'Laboratory Owner', 'business_type' => 'laboratory'],
        'logistics' => ['email' => 'logistics@taska.local', 'name' => 'Logistics Owner', 'business_type' => 'logistics'],
        'delivery_company' => ['email' => 'delivery@taska.local', 'name' => 'Delivery Owner', 'business_type' => 'delivery_company'],
        'warehouse' => ['email' => 'warehouse@taska.local', 'name' => 'Warehouse Owner', 'business_type' => 'warehouse'],
        'ngo_warehouse' => ['email' => 'ngo@taska.local', 'name' => 'Warehouse Owner', 'business_type' => 'ngo_warehouse'],
        'wholesale' => ['email' => 'wholesale@taska.local', 'name' => 'Wholesale Owner', 'business_type' => 'wholesale'],
        'commodity' => ['email' => 'commodity@taska.local', 'name' => 'Commodity Owner', 'business_type' => 'commodity'],
        'textile' => ['email' => 'textile@taska.local', 'name' => 'Textile Owner', 'business_type' => 'textile'],
        'pure_water_factory' => ['email' => 'purewaterfactory@taska.local', 'name' => 'Pure Water Factory Owner', 'business_type' => 'pure_water_factory'],
        'livestock' => ['email' => 'livestock@taska.local', 'name' => 'Livestock Owner', 'business_type' => 'livestock'],
        'farm' => ['email' => 'farm@taska.local', 'name' => 'Farm Owner', 'business_type' => 'farm'],
        'service' => ['email' => 'service@taska.local', 'name' => 'Service Owner', 'business_type' => 'service'],
        'mobile_agent' => ['email' => 'mobile@taska.local', 'name' => 'Mobile Agent Owner', 'business_type' => 'mobile_agent'],
        'school' => ['email' => 'school@taska.local', 'name' => 'School Owner', 'business_type' => 'school'],
        'construction' => ['email' => 'construction@taska.local', 'name' => 'Construction Owner', 'business_type' => 'construction'],
        'fuel_business' => ['email' => 'fuel@taska.local', 'name' => 'Fuel Owner', 'business_type' => 'fuel_business'],
        'beauty' => ['email' => 'beauty@taska.local', 'name' => 'Beauty Owner', 'business_type' => 'beauty'],
        'mixed' => ['email' => 'mixed@taska.local', 'name' => 'Mixed Business Owner', 'business_type' => 'mixed'],
        'general' => ['email' => 'general@taska.local', 'name' => 'General SME Owner', 'business_type' => 'general'],
        'pure_water_retail' => ['email' => 'purewaterretail@taska.local', 'name' => 'Pure Water Retail Owner', 'business_type' => 'pure_water_retail'],
        'cooperative' => ['email' => 'cooperative@taska.local', 'name' => 'Cooperative Owner', 'business_type' => 'general'],
    ],
    'roles' => [
        ['name' => 'Business Owner', 'slug' => 'admin', 'description' => 'Full access to all business features', 'is_default' => true],
        ['name' => 'Manager', 'slug' => 'manager', 'description' => 'Oversees daily operations', 'is_default' => false],
        ['name' => 'Cashier', 'slug' => 'cashier', 'description' => 'Handles POS and cash collection', 'is_default' => false],
        ['name' => 'Accountant', 'slug' => 'accountant', 'description' => 'Handles finance, reconciliation, and reports', 'is_default' => false],
        ['name' => 'Inventory Officer', 'slug' => 'inventory_officer', 'description' => 'Handles stock operations', 'is_default' => false],
        ['name' => 'Receptionist', 'slug' => 'receptionist', 'description' => 'Manages front desk workflows', 'is_default' => false],
        ['name' => 'Rider', 'slug' => 'rider', 'description' => 'Handles delivery assignments', 'is_default' => false],
        ['name' => 'Driver', 'slug' => 'driver', 'description' => 'Handles transport assignments', 'is_default' => false],
        ['name' => 'Staff', 'slug' => 'staff', 'description' => 'Standard staff access', 'is_default' => false],
        ['name' => 'Support Admin', 'slug' => 'support_admin', 'description' => 'Internal support access', 'is_default' => false],
    ],
];
