<?php

return [
    'types' => [
        'hotel' => [
            'profit_driver' => 'Occupancy, extra guest charges, and disciplined front-desk billing drive hotel margin.',
            'profit_killers' => ['Dirty rooms sitting idle', 'Late checkout revenue missed', 'Out-of-service rooms lingering too long'],
            'fraud_losses' => ['Manual room status changes', 'Cash leakage on walk-ins', 'Unlogged maintenance consumption'],
            'daily_decisions' => ['Which rooms need cleaning first', 'Which guests require surcharge billing', 'Which rooms must be blocked or reopened'],
            'monthly_reports' => ['Revenue by room category', 'Payment method mix', 'Occupancy trend', 'Repeat guest report'],
            'feature_highlights' => ['Housekeeping management', 'Room cleaning status', 'Maintenance requests', 'Inspection logs', 'Reservation calendar', 'Shift logs'],
        ],
        'pure_water_factory' => [
            'profit_driver' => 'Stable output with tight packaging, energy, and downtime control protects factory margin.',
            'profit_killers' => ['Leakage losses', 'Generator overuse', 'Packaging wastage', 'Untracked maintenance allocation'],
            'fraud_losses' => ['Packaging diversion', 'Fuel theft', 'Supplier balance manipulation'],
            'daily_decisions' => ['Should production run on generator or public power', 'Which packaging line is low', 'Whether output is still profitable today'],
            'monthly_reports' => ['Packaging spend report', 'Supplier spend report', 'Cost per bag trend', 'Profitability trend'],
            'feature_highlights' => ['Electricity cost tracking', 'Generator fuel logs', 'Machine runtime and downtime', 'Packaging inventory controls', 'Batch cost per sachet'],
        ],
        'school' => [
            'profit_driver' => 'Fee collection discipline and enrolment retention sustain school cash flow.',
            'profit_killers' => ['Outstanding fees', 'Poor attendance follow-up', 'Weak promotion and result control'],
            'fraud_losses' => ['Unreceipted fee collections', 'Unauthorized discounts', 'Score manipulation'],
            'daily_decisions' => ['Which students are absent', 'Which balances need follow-up', 'Which classes need staffing or timetable adjustment'],
            'monthly_reports' => ['Fee debtor report', 'Attendance rate', 'Promotion summary', 'Scholarship and discount analysis'],
            'feature_highlights' => ['Academic sessions and terms', 'Subject registration', 'Report cards', 'Promotion logic', 'Teacher assignments'],
        ],
        'clinic' => [
            'profit_driver' => 'Fast patient flow, accurate billing, and scheduled follow-up visits improve clinic revenue.',
            'profit_killers' => ['Missed appointments', 'Incomplete treatment plans', 'Uncaptured HMO claims'],
            'fraud_losses' => ['Cash receipt leakage', 'Ghost consultations', 'Manipulated bill adjustments'],
            'daily_decisions' => ['Which patients need triage first', 'Which doctors are available', 'Which follow-ups are overdue'],
            'monthly_reports' => ['Consultation revenue', 'Appointment conversion', 'HMO receivables', 'Referral source report'],
            'feature_highlights' => ['Appointments', 'Triage and vitals', 'Doctor notes', 'Diagnosis and treatment plans', 'Referral records'],
        ],
        'laboratory' => [
            'profit_driver' => 'Fast turnaround and result quality preserve lab trust and repeat business.',
            'profit_killers' => ['Rejected specimens', 'Delayed result approval', 'Poor technician utilization'],
            'fraud_losses' => ['Sample mix-ups', 'Unofficial result release', 'Billing without completed tests'],
            'daily_decisions' => ['Which samples are overdue', 'Which results need approval', 'Which technicians are overloaded'],
            'monthly_reports' => ['Turnaround time report', 'Abnormal flag trend', 'Specimen rejection log', 'Revenue by test'],
            'feature_highlights' => ['Result approval workflow', 'Technician assignment', 'Reference ranges', 'Barcode labels', 'Doctor result access'],
        ],
        'restaurant' => [
            'profit_driver' => 'Table turnover, delivery mix, and recipe margin drive restaurant performance.',
            'profit_killers' => ['Food waste', 'Poor waiter shift control', 'Underpriced takeaway and split-bill losses'],
            'fraud_losses' => ['Kitchen to POS mismatch', 'Cashier short-remittance', 'Unlogged complimentary meals'],
            'daily_decisions' => ['Which menu items are most profitable', 'Which shifts need reinforcement', 'Which orders are bottlenecked in the kitchen'],
            'monthly_reports' => ['Recipe costing', 'Waste log report', 'Order channel mix', 'Waiter shift performance'],
            'feature_highlights' => ['Waiter shifts', 'Split bills', 'Takeaway orders', 'Kitchen display board', 'Table reservations'],
        ],
        'pharmacy' => [
            'profit_driver' => 'Fast-moving medicine visibility and expiry control sustain pharmacy margin.',
            'profit_killers' => ['Near-expiry stock', 'Unmanaged generic substitution', 'Controlled drug shrinkage'],
            'fraud_losses' => ['Controlled drug diversion', 'Unauthorized discounts', 'Refill leakage without records'],
            'daily_decisions' => ['What should be discounted before expiry', 'Which substitutes are allowed', 'Which patients need refill reminders'],
            'monthly_reports' => ['Near-expiry discount report', 'Controlled drug log', 'Patient purchase history', 'Fast-moving drug trend'],
            'feature_highlights' => ['Generic and brand linkage', 'Controlled drug logs', 'Refill reminders', 'Near-expiry discounting'],
        ],
        'textile' => [
            'profit_driver' => 'Tailoring throughput and fabric conversion efficiency drive textile earnings.',
            'profit_killers' => ['Measurement mistakes', 'Idle tailoring jobs', 'Consignment stock leakage'],
            'fraud_losses' => ['Fabric diversion', 'Manual yardage underbilling', 'Cash style-order leakage'],
            'daily_decisions' => ['Which jobs are overdue', 'Which colors and variants are running low', 'Which customers need fitting follow-up'],
            'monthly_reports' => ['Tailoring job turnaround', 'Fabric variant sales', 'Consignment exposure', 'Invoice by yard trend'],
            'feature_highlights' => ['Tailoring jobs', 'Customer measurements', 'Sewing status tracking', 'Color variants', 'Consignment stock'],
        ],
        'livestock' => [
            'profit_driver' => 'Healthy herd performance, milk output, and controlled feed cost protect farm margin.',
            'profit_killers' => ['Disease outbreaks', 'Poor breeding outcomes', 'Undetected weight loss'],
            'fraud_losses' => ['Feed diversion', 'Unlogged slaughter sales', 'Medication misuse'],
            'daily_decisions' => ['Which pens need intervention', 'Which animals are underweight', 'Which medications or vaccinations are due'],
            'monthly_reports' => ['Breeding performance', 'Weight trend', 'Milk production report', 'Disease incident log'],
            'feature_highlights' => ['Weight tracking', 'Milk production', 'Disease logs', 'Medication records', 'Pen records'],
        ],
        'agro_dealer' => [
            'profit_driver' => 'Seasonal demand planning and credit recovery protect agro cash flow.',
            'profit_killers' => ['Slow subsidy receivables', 'Weak farmer credit follow-up', 'Buying wrong seasonal mix'],
            'fraud_losses' => ['Subsidy sales leakage', 'Advisory done without sales capture', 'Off-book recovery settlements'],
            'daily_decisions' => ['Which inputs to reorder by region', 'Which farmers need recovery follow-up', 'Which programmes need stock allocation'],
            'monthly_reports' => ['Seasonal demand forecast', 'Region-based sales trend', 'Farmer credit recovery report', 'Programme sales report'],
            'feature_highlights' => ['Demand forecasting', 'Government programme sales', 'Farmer credit recovery', 'Advisory records'],
        ],
        'farm' => [
            'profit_driver' => 'Healthy yield per hectare, disciplined input cost, and timely harvest conversion protect crop-farm profitability.',
            'profit_killers' => ['Input waste', 'Late planting', 'Harvest losses', 'Weak plot visibility'],
            'fraud_losses' => ['Unlogged input application', 'Harvest diversion', 'Ghost field activities'],
            'daily_decisions' => ['Which plots need input today', 'Which cycles are close to harvest', 'Where yield risk is rising'],
            'monthly_reports' => ['Yield by plot', 'Input cost trend', 'Harvest revenue report', 'Loss report'],
            'feature_highlights' => ['Farm plots', 'Planting cycles', 'Input logs', 'Harvest logs'],
        ],
        'fuel_business' => [
            'profit_driver' => 'Pump accuracy and wet stock control determine fuel station profitability.',
            'profit_killers' => ['Shift shortages', 'Wet stock variance', 'Uncontrolled price changes'],
            'fraud_losses' => ['Nozzle tampering', 'Meter manipulation', 'Attendant theft'],
            'daily_decisions' => ['Which tank needs dipping review', 'Which attendants show shortages', 'When to apply new prices'],
            'monthly_reports' => ['Wet stock variance', 'Shift shortage report', 'Price change log', 'Attendant recovery report'],
            'feature_highlights' => ['Nozzle meter readings', 'Tank dipping', 'Theft anomaly alerts', 'Shift shortages'],
        ],
        'delivery_company' => [
            'profit_driver' => 'Fast delivery completion, disciplined COD recovery, and efficient route allocation grow courier margin.',
            'profit_killers' => ['Ageing parcels', 'Delayed remittance', 'Idle fleet hours', 'Repeated failed delivery attempts'],
            'fraud_losses' => ['COD fraud', 'Fake delivery confirmation', 'Wallet payout leakage', 'Off-platform complaint resolution'],
            'daily_decisions' => ['Which parcels need manifest priority', 'Which riders hold remittance risk', 'Which routes are underperforming'],
            'monthly_reports' => ['Route efficiency report', 'Parcel ageing report', 'Complaint report', 'Rider wallet payout trend'],
            'feature_highlights' => ['OTP delivery confirmation', 'Rider wallet', 'COD fraud controls', 'Complaint management', 'Customer tracking portal'],
        ],
        'logistics' => [
            'profit_driver' => 'Trip profitability, fleet utilization, and disciplined fuel and maintenance control drive transport margin.',
            'profit_killers' => ['Empty return legs', 'Fuel overspend', 'Late maintenance', 'Trips closed without correct costing'],
            'fraud_losses' => ['Fuel diversion', 'Driver settlement leakage', 'Ghost trips', 'Under-reported customer collections'],
            'daily_decisions' => ['Which trucks should be dispatched today', 'Which trips are underperforming margin', 'Which vehicles need maintenance before the next haul', 'Which receivables are stuck after completed trips'],
            'monthly_reports' => ['Trip profitability report', 'Fuel efficiency trend', 'Maintenance cost report', 'Driver settlement report', 'Receivables ageing by trip'],
            'feature_highlights' => ['Fleet asset register', 'Trip sheets', 'Fuel logs', 'Maintenance planning', 'Driver settlements', 'Transport profitability visibility'],
        ],
        'mobile_agent' => [
            'profit_driver' => 'Transaction volume, float availability, and commission optimization sustain agent earnings.',
            'profit_killers' => ['Cash shortages', 'Delayed reversals', 'Weak float planning'],
            'fraud_losses' => ['Fraudulent transfers', 'Commission manipulation', 'Cash diversion'],
            'daily_decisions' => ['Who needs float top-up', 'Which reversals are pending', 'Which agents are underperforming'],
            'monthly_reports' => ['Float request report', 'Commission tier report', 'Fraud alert log', 'Agent ranking dashboard'],
            'feature_highlights' => ['Float requests', 'Cash shortage tracking', 'Reversal logs', 'Commission tiers', 'Agent ranking'],
        ],
        'warehouse' => [
            'profit_driver' => 'Clean stock accountability, fast request handling, and disciplined release confirmation protect warehouse performance.',
            'profit_killers' => ['Expired stock', 'Undocumented releases', 'Slow request processing'],
            'fraud_losses' => ['Waybill mismatch', 'Unsigned release confirmation', 'Stock diversion'],
            'daily_decisions' => ['Which items need redistribution before expiry', 'Which requests are urgent', 'Which releases still lack signatures'],
            'monthly_reports' => ['Stock accountability report', 'Expiry alert summary', 'Request fulfillment report', 'Release confirmation report'],
            'feature_highlights' => ['Release signatures', 'Waybill generation', 'Expiry alerts', 'Request desk visibility'],
        ],
        'ngo_warehouse' => [
            'profit_driver' => 'Clean stock accountability, fast request handling, and disciplined release confirmation protect warehouse performance.',
            'profit_killers' => ['Expired stock', 'Undocumented releases', 'Slow request processing'],
            'fraud_losses' => ['Waybill mismatch', 'Unsigned release confirmation', 'Stock diversion'],
            'daily_decisions' => ['Which items need redistribution before expiry', 'Which requests are urgent', 'Which releases still lack signatures'],
            'monthly_reports' => ['Stock accountability report', 'Expiry alert summary', 'Request fulfillment report', 'Release confirmation report'],
            'feature_highlights' => ['Release signatures', 'Waybill generation', 'Expiry alerts', 'Request desk visibility'],
        ],
        'retail' => [
            'profit_driver' => 'Fast checkout, repeat loyalty customers, and clean cashier control grow retail earnings.',
            'profit_killers' => ['Returns without control', 'Petty cash leakage', 'Slow barcode operations'],
            'fraud_losses' => ['Open shifts with no reconciliation', 'Refund abuse', 'Mixed payment leakages'],
            'daily_decisions' => ['Which cashier shifts need review', 'Which products should get barcode labels', 'Which customers deserve loyalty follow-up'],
            'monthly_reports' => ['Refund report', 'Payment method report', 'Cashier shift variance', 'Petty cash report'],
            'feature_highlights' => ['Barcode labels', 'Cashier shift open and close', 'Petty cash', 'Loyalty customers', 'Multi-payment methods'],
        ],
        'wholesale' => [
            'profit_driver' => 'Bulk pricing discipline, route-sales collection, and strong rep coverage drive distributor cash flow.',
            'profit_killers' => ['Weak route planning', 'Loose bulk discounting', 'Stock stranded in the wrong warehouse'],
            'fraud_losses' => ['Rep collection leakage', 'Unofficial customer prices', 'Transfer losses between depots'],
            'daily_decisions' => ['Which routes need stock allocation', 'Which reps are behind target', 'Which customers deserve negotiated pricing'],
            'monthly_reports' => ['Route collections report', 'Rep performance report', 'Bulk pricing trend', 'Warehouse transfer report'],
            'feature_highlights' => ['Route runs', 'Sales reps', 'Bulk price tiers', 'Stock transfers', 'Customer debt visibility'],
        ],
        'commodity' => [
            'profit_driver' => 'Buying well, grading accurately, and turning stock quickly against volatile market prices protect commodity margin.',
            'profit_killers' => ['High moisture stock', 'Shrinkage not captured', 'Idle lots waiting for better prices', 'Supplier advances without settlement discipline'],
            'fraud_losses' => ['Weighbridge manipulation', 'Manual price overrides', 'Ghost supplier settlements', 'Lot quality changed after intake'],
            'daily_decisions' => ['Which lots should be sold first', 'Whether market price moved enough to update the board', 'Which suppliers or buyers need settlement follow-up', 'Which lots have dangerous moisture or shrinkage exposure'],
            'monthly_reports' => ['Margin by commodity', 'Price board trend', 'Supplier settlement report', 'Shrinkage loss report', 'Quality grade performance'],
            'feature_highlights' => ['Lot register', 'Price board', 'Buy and sell tickets', 'Settlement tracker', 'Moisture and shrinkage control'],
        ],
        'supermarket' => [
            'profit_driver' => 'Fast barcode selling, clean cashier closeout, and strong repeat-customer behavior lift supermarket earnings.',
            'profit_killers' => ['Petty cash leakage', 'Refund abuse', 'Queue delays at busy tills'],
            'fraud_losses' => ['Barcode overrides', 'Cashier shift shortages', 'Split-payment leakage'],
            'daily_decisions' => ['Which tills need attention', 'Which stock lines are moving fastest', 'Which loyalty shoppers should be reactivated'],
            'monthly_reports' => ['Cashier shift variance', 'Payment method report', 'Refund report', 'Barcode sales trend'],
            'feature_highlights' => ['Barcode-led POS', 'Cashier shift controls', 'Loyalty customers', 'Petty cash', 'Multi-payment methods'],
        ],
        'construction' => [
            'profit_driver' => 'Tight quotation discipline, fast contractor conversion, and honest bulky-material delivery pricing protect building-material margin.',
            'profit_killers' => ['Unpriced site logistics', 'Rod and cement stockouts', 'Slow contractor debt recovery', 'Breakage losses in yard movement'],
            'fraud_losses' => ['Quote manipulation', 'Underbilled contractor prices', 'Unlogged site drop-offs', 'Diversion between warehouse, shop, and yard'],
            'daily_decisions' => ['Which quotations to chase today', 'Which contractor accounts are drifting overdue', 'Which site deliveries need trucks or loaders', 'Which categories need price changes before margin slips'],
            'monthly_reports' => ['Quotation conversion report', 'Contractor sales report', 'Debt ageing', 'Delivery report', 'Margin by category', 'Price trend report'],
            'feature_highlights' => ['Dedicated building-material categories', 'Contractor pricing', 'Truck dispatch and site delivery', 'Credit sales with ageing', 'Warehouse and yard transfers', 'Price trend control'],
        ],
        'beauty' => [
            'profit_driver' => 'Full appointment books, strong repeat-client retention, and tight product-use discipline keep salon margin healthy.',
            'profit_killers' => ['Idle chairs', 'Untracked product consumption', 'Weak rebooking discipline', 'Commission leakage'],
            'fraud_losses' => ['Cash collected outside booking flow', 'Inflated product usage', 'Unapproved discounts', 'Commission disputes'],
            'daily_decisions' => ['Which stylists need bookings', 'Which services are most profitable', 'Which products are draining margin', 'Which clients should be rebooked today'],
            'monthly_reports' => ['Revenue by service', 'Commission payout summary', 'Repeat-client trend', 'Product usage cost trend', 'Stylist productivity'],
            'feature_highlights' => ['Appointment board', 'Service catalogue', 'Product usage logging', 'Stylist commission wallet'],
        ],
        'service' => [
            'profit_driver' => 'Tight booking conversion, disciplined staff assignment, and fast invoice follow-up keep service businesses liquid.',
            'profit_killers' => ['Idle technicians', 'Completed jobs without invoicing', 'Late collections', 'Poor scheduling'],
            'fraud_losses' => ['Off-book jobs', 'Manual invoice suppression', 'Unapproved discounts', 'Ghost staff assignments'],
            'daily_decisions' => ['Which bookings need conversion into jobs', 'Which jobs must close today', 'Which clients owe invoices', 'Which staff are underutilized'],
            'monthly_reports' => ['Booking conversion report', 'Open jobs report', 'Outstanding invoices ageing', 'Staff productivity report'],
            'feature_highlights' => ['Booking desk', 'Job board', 'Staff assignments', 'Invoice follow-up controls'],
        ],
        'mixed' => [
            'profit_driver' => 'Disciplined daily cash movement, customer collection follow-up, and owner target tracking keep mixed businesses healthy.',
            'profit_killers' => ['Untracked cash outflows', 'Weak debtor follow-up', 'No daily target discipline', 'Stock and sales decisions made without visibility'],
            'fraud_losses' => ['Off-book cash collections', 'Personal expenses mixed into business cash', 'Customer balances adjusted informally', 'Manual target reporting without proof'],
            'daily_decisions' => ['Which customers need collection follow-up today', 'Whether cash out is too high against sales', 'If today is on track against sales target', 'Which branch or desk is leaking cash fastest'],
            'monthly_reports' => ['Cash-in versus cash-out trend', 'Debtor exposure report', 'Follow-up closure report', 'Daily target attainment trend', 'Owner cash discipline report'],
            'feature_highlights' => ['Cash entry log', 'Customer follow-ups', 'Daily targets', 'Collection discipline', 'Owner control centre'],
        ],
        'general' => [
            'profit_driver' => 'Disciplined daily cash movement, customer collection follow-up, and owner target tracking keep small businesses profitable.',
            'profit_killers' => ['Untracked cash outflows', 'Weak debtor follow-up', 'No daily target discipline', 'Decisions made without visible numbers'],
            'fraud_losses' => ['Off-book collections', 'Mixed personal and business spending', 'Informal balance write-offs', 'Cash receipts not captured in system'],
            'daily_decisions' => ['Which customers must be followed up today', 'Whether expense outflow is beating revenue', 'How close the business is to target', 'Which cash entries need explanation before close of day'],
            'monthly_reports' => ['Cash discipline trend', 'Collection and follow-up report', 'Debtor exposure ageing', 'Sales target attainment report', 'Expense control report'],
            'feature_highlights' => ['Cashbook pulse', 'Follow-up board', 'Daily targets', 'Owner decision cards', 'SME health dashboard'],
        ],
        'pure_water_retail' => [
            'profit_driver' => 'Fast package turnover, clean retailer pricing, and crate recovery discipline protect pure-water retail margin.',
            'profit_killers' => ['Untracked crate losses', 'Weak wholesale tier control', 'Stock stranded in the wrong outlet', 'Silent debt build-up from retailers'],
            'fraud_losses' => ['Off-book dispatches', 'Manual price overrides', 'Customer crate diversion', 'Unlogged route-drop stock movement'],
            'daily_decisions' => ['Which outlet needs fresh stock', 'Which retailers need wholesale pricing today', 'Which crates are still outside', 'Which package lines are close to stock-out'],
            'monthly_reports' => ['Retail versus wholesale mix', 'Crate accountability report', 'Package movement report', 'Outlet stock transfer trend', 'Retailer debt report'],
            'feature_highlights' => ['Package-aware price tiers', 'Sachet, bag, bottle, and crate movement tracking', 'Crate ledger', 'Retail and wholesale sales visibility'],
        ],
    ],
];
